<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SampleMcpServer.Tools</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <NoWarn>$(NoWarn);MCPEXP001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="1.2.0" />
  </ItemGroup>

</Project>
